datasets:
  - name: "FordB"
    train_file: "data/FordB/FordB_TRAIN.ts"
    test_file: "data/FordB/FordB_TEST.ts"
    combos:
      - combo_key: "scatter_plain_monochrome_with_label"
        model_type: "Deep2DCNN"
      - combo_key: "bar_border_monochrome_without_label"
        model_type: "Deep2DCNN"
      - combo_key: "area_color_with_label"
        model_type: "Simple2DCNN"
      - combo_key: "line_monochrome_without_label"
        model_type: "Simple2DCNN"
