dataset_name: "Strawberry"
num_classes: 2

models:
  - chart_type: "bar"
    bar_mode: "border"
    color_mode: "monochrome"
    label_mode: "without_label"
    combo_key: "bar_border_monochrome_without_label"
  
  - chart_type: "line"
    color_mode: "monochrome"
    label_mode: "without_label"
    combo_key: "line_monochrome_without_label"
  
  - chart_type: "area"
    color_mode: "color"
    label_mode: "with_label"
    combo_key: "area_color_with_label"
  
  - chart_type: "scatter"
    scatter_mode: "plain"
    color_mode: "monochrome"
    label_mode: "with_label"
    combo_key: "scatter_plain_monochrome_with_label"

batch_size: 32
learning_rate: 0.0003
weight_decay: 0.01
num_epochs: 150
patience: 20

# SMOTE Configuration
apply_smote: false
desired_samples_per_class: 1000  # Only used if apply_smote is true

# Validation Configuration
val_split: 0.2 