## Multibranch config file
dataset_name: "Wafer"
num_classes: 2
batch_size: 16
learning_rate: 0.0005 #0.00005
weight_decay: 0.001
num_epochs: 200
patience: 20

architecture: "DeepMultiBranchCNN" # Options: "SimpleMultiBranchCNN", "DeepMultiBranchCNN"

fusion_method: "weighted_sum" # Options: "concatenation", "weighted_sum"

numerical_processing:
  method: "oscnn" # Options: "none", "fcn", "transformer", "oscnn"
  transformer:
    num_layers: 2
    num_heads: 4
    hidden_dim: 256
    dropout: 0.1

models:
  - chart_type: "bar"
    bar_mode: "border"
    color_mode: "color"
    label_mode: "with_label"
    combo_key: "bar_border_color_with_label"

  - chart_type: "line"
    color_mode: "monochrome"
    label_mode: "with_label"
    combo_key: "line_monochrome_with_label"

  - chart_type: "area"
    color_mode: "color"
    label_mode: "with_label"
    combo_key: "area_color_with_label"

  - chart_type: "scatter"
    scatter_mode: "plain"
    color_mode: "color"
    label_mode: "with_label"
    combo_key: "scatter_plain_color_with_label"
# numerical_processing baseline:
#   method: "none" # Options: "none", "fcn", "transformer"
#   transformer:
#     num_layers: 2
#     num_heads: 4
#     hidden_dim: 128
#     dropout: 0.1

# numerical processing best parameters:
# Strawberry:
# numerical_processing:
#  method: "transformer" # Options: "none", "fcn", "transformer"
#  transformer:
#    num_layers: 5
#    num_heads: 2
#    hidden_dim: 128
#    dropout: 0.12

# ECG5000
#  numerical_processing:
#   method: "transformer" # Options: "none", "fcn", "transformer"
#   transformer:
#     num_layers: 2
#     num_heads: 4
#     hidden_dim: 128
#     dropout: 0.2

