dataset_name: "ECG5000"
num_classes: 2

batch_size: 64
learning_rate: 0.004
weight_decay: 0.01
num_epochs: 150
patience: 20

multimodal:
  enabled: true
  chart_type: "scatter"  # Choose from: bar, line, area, scatter
  color_mode: "monochrome"  # Choose from: color, monochrome
  label_mode: "without_label"  # Choose from: with_label, without_label
  scatter_mode: "plain"  # Only applicable for scatter charts
  bar_mode: "border" 

numerical_processing: 
  method: "transformer" # Choose from: fc, transformer
  transformer:
      num_layers: 5
      num_heads: 8
      hidden_dim: 64
      dropout: 0.2

# models:
#   - chart_type: "bar"
#     bar_mode: "border"
#     color_mode: "monochrome"
#     label_mode: "without_label"
#     combo_key: "bar_border_monochrome_without_label"
  
#   - chart_type: "line"
#     color_mode: "color"
#     label_mode: "without_label"
#     combo_key: "line_color_without_label"
  
#   - chart_type: "area"
#     color_mode: "color"
#     label_mode: "with_label"
#     combo_key: "area_color_with_label"
  
#   - chart_type: "scatter"
#     scatter_mode: "plain"
#     color_mode: "monochrome"
#     label_mode: "without_label"
#     combo_key: "scatter_plain_monochrome_without_label"






