dataset:
  name: Strawberry
  train_path: data/Strawberry/Strawberry_TRAIN.ts
  test_path: data/Strawberry/Strawberry_TEST.ts

image_generation:
  generate_images: true
  overwrite_existing: false

model:
  type: multi_modal_chart
  chart_model: deepcnn # simplecnn / deepcnn
  numerical_branch: fcn # none / fcn / transformer / oscnn
  fusion: weighted_sum # concat / weighted_sum
  num_classes: 2

transformer_config: # Only used if numerical_branch == transformer
  hidden_dim: 128
  num_heads: 4
  num_layers: 2
  dropout: 0.1
  output_dim: 256

chart_branches:
  branch_1:
    chart_type: area
    color_mode: color
    label_mode: with_label
  branch_2:
    chart_type: bar
    color_mode: monochrome
    label_mode: without_label
  branch_3:
    chart_type: line
    color_mode: color
    label_mode: without_label
  branch_4:
    chart_type: scatter
    color_mode: monochrome
    label_mode: without_label

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.0005

output:
  dir: results/strawberry_multimodal/
  save_model: true
