dataset:
  name: Strawberry
  train_path: data/Strawberry/Strawberry_TRAIN.ts
  test_path: data/Strawberry/Strawberry_TEST.ts

image_generation:
  generate_images: false
  overwrite_existing: false

model:
  type: multi_modal_chart # 4 charts always
  chart_model: deepcnn # simplecnn / deepcnn
  numerical_branch: transformer # none / fcn / transformer / oscnn
  fusion: concat # concat / weighted_sum
  num_classes: 2

transformer_config: # Only used if numerical_branch == transformer
  hidden_dim: 128
  num_heads: 4
  num_layers: 2
  dropout: 0.1
  output_dim: 256

chart_branches:
  branch_1:
    chart_type: area
    color_mode: color
    label_mode: with_label
  branch_2:
    chart_type: bar
    color_mode: monochrome
    label_mode: no_label
    bar_mode: border
  branch_3:
    chart_type: line
    color_mode: color
    label_mode: no_label
  branch_4:
    chart_type: scatter
    color_mode: monochrome
    label_mode: without_label
    scatter_mode: plain

training:
  batch_size: 64
  epochs: 100
  learning_rate: 0.0005

output:
  dir: results/strawberry_multimodal/
  save_model: true
