dataset:
  name: ECG5000
  train_path: data/ECG5000/ECG5000_TRAIN.ts
  test_path: data/ECG5000/ECG5000_TEST.ts

image_generation:
  generate_images: true
  overwrite_existing: true

model:
  type: single_modal_chart # single_modal_chart
  chart_model: simplecnn # simplecnn / deepcnn
  num_classes: 2

chart_branches:
  branch_1:
    chart_type: area
    color_mode: color
    label_mode: with_label

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.0005

output:
  dir: results/single_chart/
  save_model: true
