dataset:
  name: Strawberry
  train_path: data/Strawberry/Strawberry_TRAIN.ts
  test_path: data/Strawberry/Strawberry_TEST.ts

image_data:
  root_dir: charts/Strawberry_images
  chart_types:
    - line_color_without_label
    - bar_monochrome_with_label
  image_settings:
    dpi: 100
    size: [3, 3]

preprocessing:
  generate_images: true
  overwrite_existing: false

model:
  type: five_branch               # single_chart / two_branch / five_branch
  cnn_arch: deepcnn               # simplecnn / deepcnn
  numerical_branch: transformer   # none / fcn / transformer / oscnn
  fusion: dynamic_weighted_sum    # concat / dynamic_weighted_sum

training:
  batch_size: 64
  epochs: 100
  learning_rate: 0.001

output:
  dir: results/strawberry/
