dataset:
  name: Strawberry
  train_path: data/Strawberry/Strawberry_TRAIN.ts
  test_path: data/Strawberry/Strawberry_TEST.ts

image_generation:
  generate_images: true
  overwrite_existing: true

model:
  type: two_branch
  chart_model: simplecnn # simplecnn / deepcnn
  numerical_branch: transformer # fcn / transformer
  fusion: concat # concat / weighted_sum
  num_classes: 2

transformer_config:
  hidden_dim: 128
  num_heads: 4
  num_layers: 2
  dropout: 0.1
  output_dim: 256

chart_branches:
  branch_1:
    chart_type: scatter
    color_mode: monochrome
    label_mode: without_label

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.0005

output:
  dir: results/two_branch/
  save_model: true
