# models:
#   - name: Bar
#     input_channels: 3
#     num_classes: 5
#     model_type: "Simple2DCNN"
#     chart_type: "bar_border_monochrome_with_label"
#     apply_smote: false
#     smote_params:
#       1: 200
#       2: 200
#       3: 250
#       4: 300

#   - name: Area
#     input_channels: 3
#     num_classes: 5
#     model_type: "Simple2DCNN"
#     chart_type: "area_monochrome_without_label"
#     apply_smote: false
#     smote_params:
#       1: 200
#       2: 200
#       3: 250
#       4: 300

#   - name: Line
#     input_channels: 3
#     num_classes: 5
#     model_type: "Deep2DCNN"
#     chart_type: "line_color_without_label"
#     apply_smote: false
#     smote_params:
#       1: 200
#       2: 200
#       3: 250
#       4: 300

#   - name: Scatter
#     input_channels: 3
#     num_classes: 5
#     model_type: "Deep2DCNN"
#     chart_type: "scatter_plain_color_without_label"
#     apply_smote: true
#     smote_params:
#       1: 200
#       2: 200
#       3: 250
#       4: 300

# ensemble_strategy:
#   method: "majority_vote"
#   num_models: 4
models:
  - name: Bar
    input_channels: 3
    num_classes: 5
    model_type: "Deep2DCNN"
    chart_type: "bar_border_color_without_label"
    apply_smote: true
    smote_params:
      1: 200
      2: 200
      3: 250
      4: 300

  - name: Area
    input_channels: 3
    num_classes: 5
    model_type: "Deep2DCNN"
    chart_type: "area_color_without_label"
    apply_smote: true
    smote_params:
      1: 200
      2: 200
      3: 250
      4: 300

  - name: Line
    input_channels: 3
    num_classes: 5
    model_type: "Deep2DCNN"
    chart_type: "line_color_without_label"
    apply_smote: true
    smote_params:
      1: 200
      2: 200
      3: 250
      4: 300

  - name: Scatter
    input_channels: 3
    num_classes: 5
    model_type: "Deep2DCNN"
    chart_type: "scatter_plain_color_without_label"
    apply_smote: true
    smote_params:
      1: 200
      2: 200
      3: 250
      4: 300

ensemble_strategy:
  method: "majority_vote"
  num_models: 4